### ISSUE TITLE
Tabbar Ruler  has impact in performance

### ISSUE THREAD

**Issue by Distopico** [mlf176f2/tabbar-ruler.el#10]
when activated tabbar-ruler consumes 10% CPU constantly and when I turn back to its normal 0.3%

**Comment by mlf176f2** [comment]
Its because you have a hack that is constantly frying to check the mouse position by a timer.  This allows the tabbar and the menu to be displayed.  If you can figure out another way to track the mouse position, I would be happy to accept a patch.  As such, if you don't want the impact on performance, just remove the auto-hiding or changing between ruler and tabbar.

**Comment by ccordoba12** [comment]
How can I do that? I mean, what option should I add to my `.emacs`? By the way, thanks for following up this one :-)

**Comment by mlf176f2** [comment]
I downed the timer delay and made it customizable.  

You could disable the mouse-movement commands with something like
``lisp
(setq tabbar-ruler-movement-timer-dealy 1000000)
```

**Comment by ccordoba12** [comment]
Sorry for the huge delay in coming back to you @mlf176f2, but I wasn't using Emacs during these months ;-)

I can confirm that your suggested line in `.emacs` works for me. But without it, my CPU usage is even higher for the latest tabbar-ruler: something like 60% for the X server and 30% for Emacs.

Thanks a lot for the update!! Now I can use Emacs again ;-)
